### ISSUE TITLE
🚧 Library is not production ready

### ISSUE THREAD

**Issue by gordonmleigh** [awboost/cfntypes#3]
It's awesome that you've found my work, but please note that it's under development/prototyping right now as part of a broader suite of packages that I hope to release by the end of 2023. The `v1.0.0` line has a `-beta` tag and is subject to rapid change. Please don't use it for anything more than seeing what I'm up to. The `v0.*` line should be fairly stable but I don't intend to support it.

I'd love to know how you found my project and what you're using it for, please drop a comment below 👇

**Comment by ebisbe** [comment]
I'm not sure how I found it. I know I found this package first @sjmeverett/cfn-types then I had to solve some issues or make some slight changes and made a fork. And I don't remember when I found this one and was easier to use. 
Basically I'm enhancing serverless framework resources so I get them all typed.

**Comment by gordonmleigh** [comment]
I'm closing this now due to reverting the v1.x work; see [v0.100.4 Release Notes](https://github.com/awboost/cfntypes/releases/tag/v0.100.4).
