### ISSUE TITLE
Missing AWS::Serverless::Function resource

### ISSUE THREAD

**Issue by EloB** [awboost/cfntypes#5]
Thanks for making this public. I've noticed that `AWS::Serverless::Function` was missing. I think it's part of the extended version of Cloudformation from AWS.
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html

Cloudformation
https://github.com/aws/serverless-application-model/blob/develop/schema_source/cloudformation.schema.json

Cloudformation extended version with SAM
https://github.com/aws/serverless-application-model/blob/develop/schema_source/sam.schema.json

**Comment by gordonmleigh** [comment]
Hey, sorry I missed this comment. The mentioned resource is not part of CloudFormation, but SAM. SAM transforms resources using this type to normal CloudFormation resources.
